fork = false
frame = "buttonless"
idle = true
maximized = true
no-multigrid = false
neovim-bin = '/opt/homebrew/bin/nvim'
theme = "auto"
srgb = false
tabs = false
title-hidden = true
vsync = false
wsl = false
linespace = 1.2

[font]
size = 13
normal = "FiraCode Nerd Font"
style = "Regular"
