#!/bin/zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Added by Zinit's installer
ZINIT_DIR="$HOME/.local/share/zinit"
ZINIT_HOME="$ZINIT_DIR/zinit.git"
if [[ ! -f $ZINIT_HOME/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$ZINIT_DIR" && command chmod g-rwX "$ZINIT_DIR"
    command git clone https://github.com/zdharma-continuum/zinit "$ZINIT_HOME" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$ZINIT_HOME/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# Load environment variables from ~/.env if the file exists
if [ -f ~/.env ]; then
  export $(grep -v '^#' ~/.env | xargs)
fi

# Load .zsh_pre if available
zinit is-snippet for \
    if"[[ -f $HOME/.zsh_pre ]]" $HOME/.zsh_pre \
    $HOME/.dotrc/config.zsh \

#####################
# PROMPT            #
#####################
zinit ice as"command" from"gh-r" atload"eval '$(starship init zsh)'" \
  zinit light starship/starship

#####################
# PROGRAMS          #
#####################

zinit lucid light-mode from"gh-r" as"command" bpick'gitui-macos.tar.gz' for @extrawurst/gitui

zinit lucid light-mode from"gh-r" as"command" bpick'*macos*' for atload'
    eval "$(zoxide init --no-aliases zsh)"
    alias z="__zoxide_z"
' pick'zoxide/zoxide' @ajeetdsouza/zoxide

zinit lucid light-mode from"gh-r" as"command" bpick'*macos*' for @junegunn/fzf

zinit lucid light-mode from"gh-r" as"command" bpick'rg/rg' mv'ripgrep* -> rg' for @BurntSushi/ripgrep

zinit lucid light-mode from"gh-r" as"command" bpick'fd/fd' mv'fd* -> fd' for @sharkdp/fd

zinit lucid light-mode from"gh-r" as"command" bpick'bat/bat' mv'bat* -> bat' for @sharkdp/bat 

zinit lucid light-mode from"gh-r" as"command" bpick'delta/delta' mv'delta* -> delta' for @dandavison/delta

zinit lucid light-mode from"gh-r" as"command" bpick'bin/exa' for @ogham/exa 
zinit lucid light-mode from"gh-r" as"command" bpick'*macos*' for @JohnnyMorganz/StyLua

# zinit lucid light-mode from"gh-r" as"command" bpick'*macos*' for @extrawurst/gitui atinit'export PATH="$HOME/.yarn/bin:$PATH"' mv'yarn* -> yarn' pick"yarn/bin/yarn" for yarnpkg/yarn

##########################
# OMZ Libs and Plugins   #
##########################

# IMPORTANT:
# Ohmyzsh plugins and libs are loaded first as some these sets some defaults which are required later on.
# Otherwise something will look messed up
# ie. some settings help zsh-autosuggestions to clear after tab completion

setopt promptsubst

# Explanation:
# - Loading tmux first, to prevent jumps when tmux is loaded after .zshrc
# - History plugin is loaded early (as it has some defaults) to prevent empty history stack for other plugins
# zinit lucid for \
#     atinit'
#         export ZSH_TMUX_FIXTERM=false
#         export ZSH_TMUX_AUTOSTART=true
#         export ZSH_TMUX_AUTOCONNECT=true
#         export ZSH_TMUX_DEFAULT_SESSION_NAME="</>"
#     ' \
#     OMZP::tmux \
#     atinit"HIST_STAMPS=dd.mm.yyyy" \
#     OMZL::history.zsh \

zinit wait lucid for \
    OMZL::clipboard.zsh \
    OMZL::compfix.zsh \
    OMZL::completion.zsh \
    OMZL::correction.zsh \
    atload'
        alias ..="cd .."
        alias ...="cd ../.."
        alias ....="cd ../../.."
        alias .....="cd ../../../.."

        function take() {
            mkdir -p $@ && cd ${@:$#}
        }

        alias rm="rm -rf"
    ' \
    OMZL::directories.zsh \
    OMZL::git.zsh \
    OMZL::grep.zsh \
    OMZL::key-bindings.zsh \
    OMZL::spectrum.zsh \
    OMZL::functions.zsh \
    OMZL::termsupport.zsh \
    atload'
        alias gcd="git checkout dev"
        alias gce="git commit -a -e"
    ' \
    OMZP::git \
    djui/alias-tips \
    https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh \
    https://github.com/junegunn/fzf/blob/master/shell/completion.zsh \
    hlissner/zsh-autopair \
    chriskempson/base16-shell \
    OMZP::fzf \

#####################
# PLUGINS           #
#####################
# @source: https://github.com/crivotz/dot_files/blob/master/linux/zplugin/zshrc

# IMPORTANT:
# These plugins should be loaded after ohmyzsh plugins

zinit wait lucid for \
    light-mode blockf atpull'zinit creinstall -q .' \
    atinit'
        zstyle ":completion:*" completer _expand _complete _ignored _approximate
        zstyle ":completion:*" matcher-list "m:{a-z}={A-Z}"
        zstyle ":completion:*" menu select=2
        zstyle ":completion:*" select-prompt "%SScrolling active: current selection at %p%s"
        zstyle ":completion:*:descriptions" format "-- %d --"
        zstyle ":completion:*:processes" command "ps -au$USER"
        zstyle ":completion:complete:*:options" sort false
        zstyle ":fzf-tab:complete:_zlua:*" query-string input
        zstyle ":completion:*:*:*:*:processes" command "ps -u $USER -o pid,user,comm,cmd -w -w"
        zstyle ":fzf-tab:complete:kill:argument-rest" extra-opts --preview=$extract"ps --pid=$in[(w)1] -o cmd --no-headers -w -w" --preview-window=down:3:wrap
        zstyle ":fzf-tab:complete:cd:*" extra-opts --preview=$extract"exa -1 --color=always ${~ctxt[hpre]}$in"
    ' \
        zsh-users/zsh-completions \
    light-mode atinit"ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20" atload"_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions \
    light-mode atinit'
        typeset -gA FAST_HIGHLIGHT;
        FAST_HIGHLIGHT[git-cmsg-len]=100;
        zpcompinit;
        zpcdreplay;
    ' \
        zdharma-continuum/fast-syntax-highlighting \
    reset \
    atclone'local P=${${(M)OSTYPE:#*darwin*}:+g}
            \${P}sed -i \
            "/DIR/c\DIR 38;5;63;1" LS_COLORS; \
            \${P}dircolors -b LS_COLORS > c.zsh' \
    atpull'%atclone' pick"c.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"' \
        trapd00r/LS_COLORS

    # bindmap"^R -> ^H" atinit'
    #     zstyle :history-search-multi-word page-size 10
    #     zstyle :history-search-multi-word highlight-color fg=red,bold
    #     zstyle :plugin:history-search-multi-word reset-prompt-protect 1
    # ' \
    #     zdharma-continuum/history-search-multi-word \


#####################
# MANUAL CONFIG     #
#####################

# 1. Load all .zsh files under zsh/.dotrc directory
# 3. Load ~/.localrc, if it exists
# 3. Load ~/.zsh_post if it exists
zinit wait'0a' lucid is-snippet for \
    $HOME/.dotrc/extra/*.zsh \
    if"[[ -f $HOME/.localrc ]]" $HOME/.localrc


eval "$(starship init zsh)"
